{
 "title": "Borgmatic Backups",
 "description": "Dashboard for Borgmatic and Borgmatic Exporter",
 "tags": [ "backup" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_VICTORIAMETRICS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "INSTANCE",
    "label": "Instance",
    "query": {
     "query": "label_values(borg_total_backups,instance)"
    }
   },
   {
    "name": "REPOSITORY",
    "label": "Repository",
    "query": {
     "query": "label_values({instance=~\"$INSTANCE\"},repository)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Backup Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (borg_total_backups{instance=~\"$INSTANCE\"})"
    }
   ]
  },
  {
   "title": "Total Deduplicated Compressed Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (borg_total_deduplicated_compressed_size{instance=~\"$INSTANCE\"})"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "borg_last_backup_timestamp{instance=~\"$INSTANCE\"} * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "borg_last_backup_duration{instance=~\"$INSTANCE\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "borg_total_size{instance=~\"$INSTANCE\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "borg_total_deduplicated_compressed_size{instance=~\"$INSTANCE\"}",
     "legendFormat": "__auto"
    },
    { "expr": "time() * 1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (borg_total_size{instance=~\"$INSTANCE\"})"
    }
   ]
  },
  {
   "title": "Details: $REPOSITORY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "REPOSITORY",
   "collapsed": true,
   "panels": [
    {
     "title": "Backup Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(repository) (borg_total_backups{instance=~\"$INSTANCE\", repository=~\"$REPOSITORY\"})",
       "legendFormat": "{{repository}}"
      }
     ]
    },
    {
     "title": "Repo Raw Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 3, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "borg_total_size{instance=~\"$INSTANCE\", repository=~\"${REPOSITORY:raw}\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Repo Compressed Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "borg_total_compressed_size{instance=~\"$INSTANCE\", repository=~\"${REPOSITORY:raw}\"}",
       "legendFormat": "{{repository}}"
      }
     ]
    },
    {
     "title": "Repo Deduplicated and Compressed Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "borg_total_deduplicated_compressed_size{instance=~\"$INSTANCE\", repository=~\"${REPOSITORY:raw}\"}",
       "legendFormat": "{{repository}}"
      }
     ]
    },
    {
     "title": "Since Last Backup",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - max by(repository) (borg_last_backup_timestamp{instance=~\"$INSTANCE\", repository=~\"${REPOSITORY:raw}\"})",
       "legendFormat": "{{repository}}"
      }
     ]
    },
    {
     "title": "Last Backup Raw Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 3, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "borg_last_backup_size{instance=~\"$INSTANCE\", repository=~\"${REPOSITORY:raw}\"}",
       "legendFormat": "{{repository}}"
      }
     ]
    },
    {
     "title": "Last Backup Compressed Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "borg_last_backup_compressed_size{instance=~\"$INSTANCE\", repository=~\"${REPOSITORY:raw}\"}",
       "legendFormat": "{{repository}}"
      }
     ]
    },
    {
     "title": "Last Backup Deduplicated and Compressed Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "borg_last_backup_deduplicated_compressed_size{instance=~\"$INSTANCE\", repository=~\"${REPOSITORY:raw}\"}",
       "legendFormat": "{{repository}}"
      }
     ]
    },
    {
     "title": "Last Backup Timestamp",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(repository) (borg_last_backup_timestamp{instance=~\"$INSTANCE\", repository=~\"${REPOSITORY:raw}\"} * 1000)",
       "legendFormat": "{{repository}}"
      }
     ]
    },
    {
     "title": "Last Backup Files",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 3, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "borg_last_backup_files{instance=~\"$INSTANCE\", repository=~\"${REPOSITORY:raw}\"}",
       "legendFormat": "{{repository}}"
      }
     ]
    },
    {
     "title": "Last Backup Duration (s)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 22 },
     "targets": [
      {
       "expr": "borg_last_backup_duration{instance=~\"$INSTANCE\", repository=~\"${REPOSITORY:raw}\"}",
       "legendFormat": "{{repository}}"
      }
     ]
    }
   ]
  }
 ]
}